### ISSUE TITLE
autoExport does not update export policies for PVCs created from snapshots

### ISSUE THREAD

**Issue by bucklo** [NetApp/trident#1016]
**Describe the bug**
When using autoExport and creating a new PVC from a snapshot, the new PVC retains the original export policies from the source volume instead of updating them based on the node where the new pod is scheduled. This prevents pods scheduled on different nodes from accessing the volume created from the snapshot.

**Environment**
- Trident version: 25.02.0
- Trident installation flags used: trident-operator
- Container runtime: cri-o://1.31.8-4.rhaos4.18.git2d48ec9.el9
- Kubernetes version: v1.31.8
- Kubernetes orchestrator: OpenShift
- OS: Red Hat Enterprise Linux CoreOS 418.94.202505191717-0
- NetApp backend types: ONTAP-NAS
- Other: N/A

**To Reproduce**

1. Create a PVC using the following storage class:
   ```yaml
   allowVolumeExpansion: true
   apiVersion: storage.k8s.io/v1
   kind: StorageClass
   metadata:
     name: trident-sc
   provisioner: csi.trident.netapp.io
   reclaimPolicy: Delete
   volumeBindingMode: Immediate
   ```

2. Create a pod that mounts this PVC and pin it to a specific node using `.spec.nodeName`
   ```yaml
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: test-pvc
     namespace: default
   spec:
     accessModes:
     - ReadWriteMany
     resources:
       requests:
         storage: 1Gi
     storageClassName: trident-sc
   ---
   apiVersion: v1
   kind: Pod
   metadata:
     name: test-pod-001
   spec:
     nodeName: k8s-node-001
     containers:
     - name: httpd
       image: httpd:latest
       volumeMounts:
       - name: my-storage
         mountPath: /tmp/test
   volumes:
   - name: my-storage
      persistentVolumeClaim:
        claimName: test-pvc
   ```

3. Trident automatically assigns export policy with the node IP where the pod is running

4. Create a VolumeSnapshot of the original PVC
   ```yaml
   apiVersion: snapshot.storage.k8s.io/v1
   kind: VolumeSnapshot
   metadata:
     name: test-snap
   spec:
     volumeSnapshotClassName: csi-trident-vsc
     source:
       persistentVolumeClaimName: test-pvc
   ```
5. Create a new PVC using the VolumeSnapshot as dataSource
   ```yaml
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: pvc-from-snap
   spec:
     accessModes:
     - ReadWriteMany
     storageClassName: trident-sc
     resources:
       requests:
         storage: 1Gi
     dataSource:
       name: test-snap
       kind: VolumeSnapshot
       apiGroup: snapshot.storage.k8s.io
   ```
6. Create a new pod that mounts the new PVC and pin it to a **different** node using `.spec.nodeName`
   ```yaml
   apiVersion: v1
   kind: Pod
   metadata:
     name: test-pod-002
   spec:
     nodeName: k8s-node-002
     containers:
     - name: httpd
       image: httpd:latest
       volumeMounts:
       - name: my-storage
         mountPath: /tmp/test
   volumes:
   - name: my-storage
      persistentVolumeClaim:
        claimName: pvc-from-snap
   ```
7. Observe that the pod cannot access the volume because the export policy still contains only the original node's IP

**Expected behavior**
When a new PVC is created from a snapshot and mounted on a pod running on a different node, Trident should update the export policy to include the new node's IP address, allowing the pod to access the volume.

**Additional context**
- The issue occurs consistently every time a pod mounting the new PVC is started on a node different from the original export policy
- Re-creating the pod does not resolve the issue
- No relevant log entries regarding export policies were found in Trident logs
- This behavior breaks the expected autoExport functionality for volumes created from snapshots
- The new volume is successfully provisioned in ONTAP, but the export policy is not updated to reflect the new pod's node location
