### ISSUE TITLE
Trident bug in provisioning with Kubernetes.

### ISSUE THREAD

**Issue by dsmithfv** [NetApp/trident#133]
As documented in: https://github.com/NetApp/trident/issues/101

"The iSCSI driver doesn't delete a device upon detach as there is no rescan following unmount."

Looking at K8s documentation I noticed Trident is failing to set the portals setting for LUNS.  We performed testing and found that setting the portals resolves this issue.  Below is a snippet of our pv configuration.

```
iscsi:
  fsType: ext4
  iqn: iqn.1992-08.com.netapp:sn.12345678910:vs.4
  iscsiInterface: default
  lun: 6
  targetPortal: 10.28.52.128
  portals:
  - 10.28.52.128
  - 10.28.52.129
  - 10.28.52.130
  - 10.28.52.131
  - 10.28.52.136
  - 10.28.52.137
  - 10.28.52.138
  - 10.28.52.139
```

After manually creating a pv and pvc connected to the Ontap the ISCSI device was removed as expected.
Using Trident to dynamically provision it did not. Is it possible to update Trident to add the additional paths to the portal section above?
