### ISSUE TITLE
Cannot change junction_path of volume

### ISSUE THREAD

**Issue by simonpie** [NetApp/trident#220]
I am trying to change the junction path of a volume.  Either at renaming of the volume, or as a stand alone operation.

When trying to change the junction path of a volume, it does not work.  Rerun of the playbook will not work either.  Trying just a new name will not work either.  Name changing of the volume works fine.
```
 - name: Volume rename
    na_ontap_volume:
      state: present
      from_name: "{{ from_name }}"
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{aggr }}"
      size: 3
      size_unit: gb
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
```

Running on a fully patch mac : 
sw_vers                                                 
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

ansible-playbook --version
ansible-playbook 2.7.8

pip list | grep -i netap         
netapp-lib                         2018.11.13 

python --version
Python 2.7.15
