### ISSUE TITLE
etcd container stops working aproximately every 20-30 minutes

### ISSUE THREAD

**Issue by felixkrohn** [NetApp/trident#249]
About every 20 minutes, the etcd container is restarted after the liveness probes fail:

`etcdctl -endpoint=http://127.0.0.1:8001/ cluster-health` gives:
> member 9ca0c7938a0c3dc5 is unhealthy: got unhealthy result from http://127.0.0.1:8001
> cluster is unavailable

`ETCDCTL_API=3 etcdctl endpoint health --endpoints=localhost:8001` gives:
> localhost:8001 is unhealthy: failed to commit proposal: context deadline exceeded
> Error: unhealthy cluster

The etcd container is restarted seconds later by Openshift after the liveness probe fails.
Environment:
- Openshift Enterprise 3.11
- trident v19.04.1, etcd 3.3.12
- trident PV is on Netapp ontap-nas, mounted over NFS v4.0

We see this happening since more than a month now and couldn't find a reason for this. I'm not sure if it started with update to v18.07.0 where liveness probes were included, or around the same time due to other reasons. It seems to happen 

Any hints on how to proceed to further debug this?

To give a sense of the almost perfect regularity of these events, here are the etcd container restarts this night:
2019-05-08 19:58:01
2019-05-08 20:19:07
2019-05-08 20:40:53
2019-05-08 21:01:00
2019-05-08 21:22:06
2019-05-08 21:43:44
2019-05-08 22:06:56
2019-05-08 22:30:40
2019-05-08 22:52:35
2019-05-08 23:13:45
2019-05-08 23:35:16
2019-05-08 23:55:31
2019-05-09 00:16:35
2019-05-09 00:40:04
2019-05-09 01:02:03
2019-05-09 01:22:27
2019-05-09 02:03:18
2019-05-09 02:24:03
2019-05-09 02:45:58
2019-05-09 03:06:03
2019-05-09 03:27:07
2019-05-09 03:48:49
2019-05-09 04:09:25
2019-05-09 04:30:33
2019-05-09 04:51:34
2019-05-09 05:12:12
2019-05-09 05:33:18
2019-05-09 05:54:22
2019-05-09 06:16:00
2019-05-09 06:36:18
2019-05-09 06:57:03
2019-05-09 07:18:06

**Comment by kangarlou** [comment]
Can you examine the kubelet logs? What version of Docker are you running?
I also suspect this is due to liveness probes and possibly related to https://access.redhat.com/solutions/3734981.

To confirm liveness probes are indeed the culprit, you can disable the liveness probes by following these steps:
1. Generate the `deployment.yaml` by running below command (This command will not install trident but only generate the yaml files under trident-installer/setup folder)–
```
root@scs:~/trident-installer# tridentctl install --generate-custom-yaml -n trident
INFO Wrote installation YAML files.                setupPath=/root/trident-installer/setup
``` 
2. Update the `trident-deployment.yam`’ file by removing following section:
```
root@scs:~/trident-installer# vi ~/trident-installer/setup/trident-deployment.yaml
[Remove the following from ‘etcd’]
 
        livenessProbe:
          exec:
            command:
            - etcdctl
            - -endpoint=http://127.0.0.1:8001/
            - cluster-health
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 10
```
3. Re-install the trident with updated custom `deployment.yaml` by running follwoing command:
```
root@scs:~/trident-installer# tridentctl install --use-custom-yaml ~/trident-installer/setup/ trident-deployment.yaml -n trident
```
