### ISSUE TITLE
pv on existing netapp volume not listed by tridentctl

### ISSUE THREAD

**Issue by wu105** [NetApp/trident#255]
We cloned a volume in netapp, then created a k8s pv on it which specified the trident storageClass `basic`, see below.  'tridentctl get volume' does not list anything related to such a pv.  Is this expected?  If so, is there a way to get such pv registered with trident?

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: netapp.io/trident
    volume.beta.kubernetes.io/storage-class: basic
  finalizers:
  - kubernetes.io/pv-protection
  name: devops-blah
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /trident_devops_blah
    server: 192.168.12.34
  persistentVolumeReclaimPolicy: Retain
  storageClassName: basic
```
