### ISSUE TITLE
failed in resizing the volume or PV: unable to resize the volume: volume XXX does not exist

### ISSUE THREAD

**Issue by geoberle** [NetApp/trident#297]
We are running trident 18.10 with nas economy backend on top of OpenShift 3.11 and faced the following warning during a PVC resize

failed in resizing the volume or PV: unable to resize the volume: volume XXX does not exist

we verified with "tridentctl get volume XXX" that the volume exists but saw something interesting when getting details with -o yaml

```
items:
- Config:
    accessInformation:
      nfsPath: /_____/____
      nfsServerIp: _._._._
    accessMode: ReadWriteMany
    blockSize: ""
    cloneSourceSnapshot: ""
    cloneSourceVolume: ""
    cloneSourceVolumeInternal: ""
    encryption: ""
    fileSystem: ext4
    internalName: trident________
    name: ___
    protocol: file
    securityStyle: ""
    size: "537919488"
    spaceReserve: ""
    splitOnClone: ""
    storageClass: basic
    version: "1"
  backend: ontapnaseco__._._._
  orphaned: true
  pool: data01_01_SATA4000
```

the volume is orphaned. what does orphaned mean? how can we fix it? 

the qtree itself is there, can be mounted and works just fine.
