### ISSUE TITLE
Install v19.10.0 on Openshift (run as root)

### ISSUE THREAD

**Issue by josgonza-rh** [NetApp/trident#338]
In previous versions of the Trident installer (at least till v19.01.0 version), one of the steps of the installer was to add the `Service Account` **trindent** to the `SCC` **anyuid** (so the container could run as root).

In `v19.10.0` version this step is not done so if you are in a restricted environment (the default `SCC` has the `MustRunAsNonRoot` policy) the deploy of the container fails as the docker image, that it doesn't have an `USER` directive, tries to run as **root**.

Here we have 2 approach:

1. Modifying the image following the best practices described in the **OKD** documentation [here](https://docs.okd.io/latest/creating_images/guidelines.html).
2. Modifying the current `Cluster Role` to levereage Role-Based Access feature (GA since 3.11 and above).

The Role-Based Access to SCCs approach it is the _easiest_ of the two and has an advantage over the oldest approach (v19.01.0 and previous versions):
- You don’t need to change the SCC object (groups and users fields)
- Avoid losing all those assignments if you update the SCC

The following lines should be added to the current `Cluster Role` **Trident**:

```yml
... ommited...
rules:
- apiGroups:
  - security.openshift.io 
  resources:
  - securitycontextconstraints 
  verbs:
  - use
  resourceNames:
  - {{ SCC }}
... ommited...
```
>NOTE: SCC value could be **anyuid** (as the default value) or a custom value passed as an argument to the `trindentctl` command.
