### ISSUE TITLE
Update SolidFire backend to allow CHAP authentication

### ISSUE THREAD

**Issue by dutchiechris** [NetApp/trident#42]
As of Trident v17.07.0 when using SolidFire up to 4 volume access groups (VAGs) can be configured; see https://github.com/NetApp/trident/issues/24.  This fix allows the k8s admin to configure up to 74 k8s nodes per VAG, or 256 nodes in total.  Larger k8s cluster sizes are not possible, and managing k8s nodes in those VAGs is a task left to the k8s admin [instead of managed by Trident] which is extra work and gives the potential for mistakes.

In k8s 1.7 support for [CHAP authentication on iSCSI volumes](https://github.com/kubernetes/examples/tree/master/staging/volumes/iscsi) was introduced.  If Trident were to support CHAP authentation it would resolve the two previously mentioned limitations.

Using the example from the aforementioned k8s docs I was able to manually use CHAP authentication with SolidFire:

```
# cat chap-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-ro
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsivol
  volumes:
  - name: iscsivol
    iscsi:
      targetPortal: 192.168.1.190
      iqn: iqn.2010-01.com.solidfire:pnay.chaptest.2567
      lun: 0
      fsType: ext4
      readOnly: false
      chapAuthDiscovery: true
      chapAuthSession: true
      secretRef:
         name: chap-secret

# cat chap-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: chap-secret
type: "kubernetes.io/iscsi-chap"
data:
  discovery.sendtargets.auth.username: azhzLWNoYXA=
  discovery.sendtargets.auth.password: azhzLWNoYXAtaW5pdA==
  discovery.sendtargets.auth.username_in: azhzLWNoYXA=
  discovery.sendtargets.auth.password_in: azhzLWNoYXAtdGFyZ2V0
  node.session.auth.username: azhzLWNoYXA=
  node.session.auth.password: azhzLWNoYXAtaW5pdA==
  node.session.auth.username_in: azhzLWNoYXA=
  node.session.auth.password_in: azhzLWNoYXAtdGFyZ2V0
```

To complete the `Secret` data section use `echo -n "value-to-encode" | base64` and put that output into the appropriate field:

```
discovery.sendtargets.auth.username = <SolidFire Account Name>
discovery.sendtargets.auth.password = <SolidFire Account Initiator Secret>
discovery.sendtargets.auth.username_in = <SolidFire Account Name>
discovery.sendtargets.auth.password_in = <SolidFire Account Target Secret>
node.session.auth.username = <SolidFire Account Name>
node.session.auth.password = <SolidFire Account Initiator Secret>
node.session.auth.username_in = <SolidFire Account Name>
node.session.auth.password_in = <SolidFire Account Target Secret>
```
