### ISSUE TITLE
[Trident Operator] Service account not created

### ISSUE THREAD

**Issue by stobias123** [NetApp/trident#426]
**Describe the bug**
Operator install fails on openshift 4.5.

The operator fails with this line
```bash
time="2020-08-02T18:18:10Z" level=error msg="Object creation failed." err="ServiceAccount \"trident-csi\" is invalid: metadata.labels: Invalid value: \"v1.18.3+012b3ec\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" yamlDocument="---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: trident-csi\n  labels:\n    app: controller.csi.trident.netapp.io\n    k8s_version: v1.18.3+012b3ec\n    trident_version: v20.04\n  ownerReferences:\n  - apiVersion: trident.netapp.io/v1\n    controller: true\n    kind: TridentProvisioner\n    name: trident\n    uid: fa73e2f0-e707-4f3e-a914-b0fa12994878\n"
```

The rendered (prettified) service account manifest looks like this.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-csi
  labels:
    app: controller.csi.trident.netapp.io
    k8s_version: v1.18.3+012b3ec
    trident_version: v20.04
  ownerReferences:
  - apiVersion: trident.netapp.io/v1
    controller: true
    kind: TridentProvisioner
    name: trident
    uid: fa73e2f0-e707-4f3e-a914-b0fa12994878
```

This `k8s_version` label is broken due to the "+".

Why is this label even needed?

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.04
- Trident installation flags used: n/a
- Container runtime: crio
- Kubernetes version: v1.18.3+012b3ec
- Kubernetes orchestrator: Openshift 4.5
- NetApp backend types: N/A
- Other:

**To Reproduce**
Install operator on a 4.5 cluster or a cluster with a funky version string.

**Expected behavior**
I expect trident to install properly.
