### ISSUE TITLE
Attaching static provisoned Netapp volume with pod

### ISSUE THREAD

**Issue by kannanvr** [NetApp/trident#509]
Hi,
   We are facing one of the issue.
I am able to bring up the ontap-nas backend with Netapp Trident.

```
[root@k8s-master01 trident-installer]# ./tridentctl -n trident get backend
+-------------------+----------------+--------------------------------------+--------+---------+
|       NAME        | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------+----------------+--------------------------------------+--------+---------+
| customBackendName | ontap-nas      | xxxxxxxxxxxxx-xxxx | online |       1 |
+-------------------+----------------+--------------------------------------+--------+---------+

````
I have created the Storage class as below . We don't want to go for Dynamic provison on our ontap. we have created the static volume on the SVM.

Static volume name as kubetest2 and we have created the PV as below

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-static-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: basic
  csi:
    driver: csi.trident.netapp.io
    volumeAttributes:
      backendUUID: xxxxxxxxxxxxx-xxxx
      internalName: kubetest2
      name: kubetest2
      protocol: file
    volumeHandle: kubetest2
```

When we create the PVC with the same name, its status is Bound. When we are trying to attach within pod we are getting the below error from trident csi pod

```


time="2021-01-19T10:09:33Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=63814aa8-694a-47f2-aa59-932639ea85db requestSource=CSI
time="2021-01-19T10:09:33Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=78462773-f3e0-4c4d-89f5-3142bad11d85 requestSource=CSI
time="2021-01-19T10:09:33Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=bd92179a-a3a4-4346-8126-5125f6bc11de requestSource=CSI
time="2021-01-19T10:09:43Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=9696c6a9-66ef-4a3e-9b25-27d731106f1c requestSource=CSI
time="2021-01-19T10:09:43Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=f4b3b9d4-1da4-436e-9933-091fd3869fd1 requestSource=CSI
time="2021-01-19T10:10:23Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=48723f42-61b4-40a1-bed4-7bb3a63cb920 requestSource=CSI
time="2021-01-19T10:11:03Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=8d579df5-b64d-4c75-891b-a02d7948c823 requestSource=CSI
time="2021-01-19T10:11:43Z" level=error msg="GRPC error: rpc error: code = NotFound desc = volume kubetest2 was not found" requestID=9fd67b1f-9316-43be-9e68-6a4dbb172e72 requestSource=CSI

````
Kindly provide the solution for this issue.
Here we wanted to attach the volume created by statically by using the Trident

Thanks,
Kannan V
