### ISSUE TITLE
Auto-install dependencies cannot parse OS version

### ISSUE THREAD

**Issue by yp28** [NetApp/trident#577]
**Describe the bug**
When using the [automatic worker node preparation beta feature](https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/concepts/workernodeprep.html?highlight=node-prep), Trident fails to correctly parse the OS version number.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.10
- Trident installation flags used: /
- Container runtime: Docker 19.03.15-CE
- Kubernetes version: 1.19.6
- Kubernetes orchestrator: Rancher v2.5.5
- Kubernetes enabled feature gates: /
- OS: RHEL 7.9
- NetApp backend types: /

**To Reproduce**
Deploy the following `TridentProvisioner` after installing the Trident Operator:
```yaml
apiVersion: trident.netapp.io/v1
kind: TridentProvisioner
metadata:
  name: trident
  namespace: trident
spec:
  debug: true
  enableNodePrep: true
  silenceAutosupport: true
```
Outputs the following:
`error preparing iSCSI packages on the host; error checking for installed packages; error checking for package on host; error determining host's package manager; error parsing OS version; strconv.ParseInt: parsing "7.9": invalid syntax`

**Expected behavior**
I expect the Trident CSI driver to install the necessary packages for it to work.

**Additional context**
/
