### ISSUE TITLE
Deprecated csidrivers.v1beta1.storage.k8s.io API used

### ISSUE THREAD

**Issue by Numblesix** [NetApp/trident#628]
Hello

im using trident in version v21.07.01 on OpenShift 4.8 (k8s: v1.21.1+9807387) and i see a warning that Trident uses an API that will be removed in K8s 1.22 :)      
Is it already planned to remove this API for the next release of Trident :) ?

```yaml
apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  generation: 1
  name: csidrivers.v1beta1.storage.k8s.io
spec:
  numberOfUsersToReport: 10
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 10
          verb: list
        - requestCount: 5
          verb: patch
        requestCount: 15
        userAgent: trident-operator/v0.0.0
        username: system:serviceaccount:trident:trident-operator
      nodeName: 1.2.3.4
      requestCount: 15
    requestCount: 15
```

BR,
Numblesix
