### ISSUE TITLE
New vpc on solidfire backend doesn't work

### ISSUE THREAD

**Issue by nheinemans** [NetApp/trident#642]
**Describe the bug**
This used to work on trident operator version 20.10. After upgrading to 21.07.1, we started seeing this issue.
Creating a new PVC, the lun is created correctly on solidfire, and shown in kubectl get pvc. However, when starting a pod using this pvc, we get the error message:
` MountVolume.MountDevice failed for volume "pvc-e8ab7e36-9438-41ba-9a75-5ace445f40d3" : rpc error: code = Internal desc = iSCSI login failed using CHAP`
When checking the iscsi node file (under /var/lib/iscsi/nodes on the worker node), it contains this line:
`node.session.auth.authmethod = None`
I believe this should be CHAP instead of None

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 21.07.1
- Trident installation flags used: 
- Container runtime: Docker 19.03.15
- Kubernetes version: 1.19.6
- Kubernetes orchestrator: Rancher 2.5.9
- Kubernetes enabled feature gates: 
- OS: RHEL 7.9
- NetApp backend types: Solidfire
- Other:

**To Reproduce**
Create PVC, create pod

**Expected behavior**
Running pod with PVC mounted as a filesystem

**Additional context**
Configured the trident-operator with these settings:
```
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  silenceAutosupport: true
  namespace: trident
  imageRegistry: <internal repo>/sig-storage
  autosupportImage: <internal repo>/netapp/trident-autosupport:21.01
  tridentImage: <internal repo>/netapp/trident:21.07.1
```

Configured backend with this yaml:
```
version: 1
storageDriverName: solidfire-san
backendName: <name>
Endpoint: https://user:pass@<solidfire mgmt hostname>/json-rpc/8.0
SVIP: <solidfire storage hostname>:3260
TenantName: <tenant>
UseCHAP: true
Types:
- Type: Bronze
  QoS:
    minIOPS: 1000
    maxIOPS: 2000
    burstIOPS: 4000
type: solidfire
region: <region>
zone: <zone>
storage:
- labels:
    performance: Bronze
  type: Bronze
```
