### ISSUE TITLE
Not able to create san backend with FSx for NetApp ONTAP

### ISSUE THREAD

**Issue by paalkr** [NetApp/trident#647]
**Describe the bug**
The AWS FSx for NetApp ONTAP provided DNS name for the iscsi dataLIF is not allowed to use in a san backend configuration.
I tried to follow this guide (https://github.com/NetApp/trident/blob/8e7b85928d6a7cd9f14f62aa96493630b45f6449/docs/kubernetes/fsx.rst#configuration) to create a san backend.

Trident refuses to create the backend with the following error message
`Warning  Failed  2s (x12 over 15s)  trident-crd-controller  Failed to create backend: problem initializing storage driver 'ontap-san-economy': error initializing ontap-san-economy driver: error driver validation failed: data LIF is not a valid IP: iscsi.svm-xxxxxxx.fs-yyyyyyy.fsx.eu-north-1.amazonaws.com`

**Environment**
Vanilla Kubernetes 1.19.14 deployed to AWS using kOps 1.21.0

- Trident version: [e.g. 19.10]
21.07
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml]
`helm install -n kube-netapp trident .\trident-operator-chart-21.07\ -f .\values.yaml`
- Container runtime: [e.g. Docker 19.03.1-CE]
Docker 20.10.7
- Kubernetes version: [e.g. 1.15.1]
1.19.14
- Kubernetes orchestrator: [e.g. OpenShift v3.11, Rancher v2.3.3]
kOps 1.21.0
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
None
- OS: [e.g. RHEL 7.6, Ubuntu 16.04]
Ubuntu 20.04.2 LTS
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7]
AWS FSx for NetApp ONTAP
- Other:

This is my backend spec
```
apiVersion: v1
kind: Secret
metadata:
  name: fsx-netapp-1-k8s1-san-eco-chap
type: Opaque
stringData:
  username: vsadmin
  password: "xxx"
  chapInitiatorSecret: yyy
  chapUsername: zzz
  chapTargetInitiatorSecret: fff
  chapTargetUsername: bbb
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: fsx-netapp-1-k8s1-san-eco
spec:
  version: 1
  storageDriverName: ontap-san-economy
  managementLIF: "svm-xxxxxxx.fs-yyyyyyy.fsx.eu-north-1.amazonaws.com"
  dataLIF: "iscsi.svm-xxxxxxx.fs-yyyyyyy.fsx.eu-north-1.amazonaws.com"
  storagePrefix: k8s1
  autoExportPolicy: true
  igroupName: trident
  autoExportCIDRs: ["10.26.0.0/16"]
  svm: k8s1-2
  useCHAP: true
  credentials: 
    name: fsx-netapp-1-k8s1-san-eco-chap
  defaults:
    tieringPolicy: auto
```

**Comment by balaramesh** [comment]
The error indicates that Trident is unable to communicate with the backend. More specifically, the dataLIF is not reachable. Can you check to see if the dataLIF configured in the backend definition is accurate? Can you ping the dataLIF from a node in the k8s cluster?

**Comment by paalkr** [comment]
I can see this in the debug log from the trident-main container, so I think connectivity is working. The trident controller manages to get the dataLIF IPs from the SVM. Also the aggr1 information is fetch correctly.
```
time="2021-09-23T21:13:40Z" level=debug msg="Data LIFs" crdControllerEvent=add dataLIFs="[10.26.159.53 10.26.181.56]" requestID=981f8fce-4003-4a14-a370-e46dba4afbcd requestSource=CRD
time="2021-09-23T21:13:40Z" level=debug msg="Found iSCSI LIFs." crdControllerEvent=add dataLIFs="[10.26.159.53 10.26.181.56]" requestID=981f8fce-4003-4a14-a370-e46dba4afbcd requestSource=CRD
time="2021-09-23T21:13:40Z" level=debug msg="SAN Economy driver settings." FlexvolNamePrefix=trident_lun_pool_trident_ LUNsPerFlexvol=100 crdControllerEvent=add requestID=981f8fce-4003-4a14-a370-e46dba4afbcd requestSource=CRD
time="2021-09-23T21:13:40Z" level=debug msg="Read storage pools assigned to SVM." crdControllerEvent=add pools="[aggr1]" requestID=981f8fce-4003-4a14-a370-e46dba4afbcd requestSource=CRD svm=k8s1-2
time="2021-09-23T21:13:40Z" level=debug msg="Node updated in cache." name=ip-10-26-195-187.eu-north-1.compute.internal requestID=493d7c2f-4ae9-4b93-ad45-aea9ce4f744d requestSource=Kubernetes
time="2021-09-23T21:13:40Z" level=debug msg="Aggregate has unknown performance characteristics." aggregate=aggr1 crdControllerEvent=add mediaType=vmdisk requestID=981f8fce-4003-4a14-a370-e46dba4afbcd requestSource=CRD
time="2021-09-23T21:13:40Z" level=debug msg=NewLabelOffer offers="map[]"
time="2021-09-23T21:13:40Z" level=debug msg="No such initiator group (igroup)." crdControllerEvent=add igroup=trident requestID=981f8fce-4003-4a14-a370-e46dba4afbcd requestSource=CRD
time="2021-09-23T21:13:40Z" level=error msg="Could not initialize storage driver." crdControllerEvent=add error="error initializing ontap-san-economy driver: error driver validation failed: data LIF is not a valid IP: iscsi.svm-0ec85cf5ae6c7d6bb.fs-03f11a349bc1e427b.fsx.eu-north-1.amazonaws.com" requestID=981f8fce-4003-4a14-a370-e46dba4afbcd requestSource=CRD
```

In addition I have the nas driver setup and working perfectly on the same cluster, same trident installation and the same FSx backend.

**Comment by paalkr** [comment]
I can ping both the managementLIF and the dataLIF DNS names from a random k8s node. Both resolves correctly and works.

```
ubuntu@ip-10-26-137-184:~$ ping svm-0ec85cf5ae6c7d6bb.fs-03f11a349bc1e427b.fsx.eu-north-1.amazonaws.com
PING svm-0ec85cf5ae6c7d6bb.fs-03f11a349bc1e427b.fsx.eu-north-1.amazonaws.com (198.19.255.5) 56(84) bytes of data.
64 bytes from 198.19.255.5 (198.19.255.5): icmp_seq=1 ttl=64 time=0.171 ms
64 bytes from 198.19.255.5 (198.19.255.5): icmp_seq=2 ttl=64 time=0.152 ms
^C
--- svm-0ec85cf5ae6c7d6bb.fs-03f11a349bc1e427b.fsx.eu-north-1.amazonaws.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.152/0.161/0.171/0.009 ms
ubuntu@ip-10-26-137-184:~$ ping iscsi.svm-0ec85cf5ae6c7d6bb.fs-03f11a349bc1e427b.fsx.eu-north-1.amazonaws.com
PING iscsi.svm-0ec85cf5ae6c7d6bb.fs-03f11a349bc1e427b.fsx.eu-north-1.amazonaws.com (10.26.159.53) 56(84) bytes of data.
64 bytes from ip-10-26-159-53.eu-north-1.compute.internal (10.26.159.53): icmp_seq=1 ttl=64 time=0.143 ms
64 bytes from ip-10-26-159-53.eu-north-1.compute.internal (10.26.159.53): icmp_seq=2 ttl=64 time=0.108 ms
64 bytes from ip-10-26-159-53.eu-north-1.compute.internal (10.26.159.53): icmp_seq=3 ttl=64 time=0.124 ms
```

**Comment by paalkr** [comment]
OK, I managed to register the backend. It turns out that the documentation added by this commit https://github.com/NetApp/trident/commit/c3f9b53293121d28a7a34f6c1b6723ba19724c80 is wrong



Looking at the source code indicated that you cannot specify a FQDN as dataLIF as described in the documentation at [line 84](https://github.com/NetApp/trident/blame/master/docs/kubernetes/fsx.rst#L84) . 
https://github.com/NetApp/trident/blob/8e7b85928d6a7cd9f14f62aa96493630b45f6449/storage_drivers/ontap/ontap_common.go#L1273-L1277

Removing the dataLIF from my backend config works. Trident then automatically lookup the dataLIF from the SVM, and the backend registers.
```
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: fsx-netapp-1-k8s1-san-eco
spec:
  version: 1
  storageDriverName: ontap-san-economy
  managementLIF: "svm-xxx.fs-yyy.fsx.eu-north-1.amazonaws.com"
  # dataLIF: "iscsi.svm-xxx.fs-yyy.fsx.eu-north-1.amazonaws.com"
  storagePrefix: k8s1
  autoExportPolicy: true
  igroupName: trident
  autoExportCIDRs: ["10.26.0.0/16"]
  svm: k8s1-2
  useCHAP: true
  credentials: 
    name: fsx-netapp-1-k8s1-san-eco-chap
  defaults:
    tieringPolicy: auto
```

```
Status:
  Backend Info:
    Backend Name:         fsx-netapp-1-k8s1-san-eco
    Backend UUID:         3cda4856-a13f-4d47-b7c0-30eac32924c0
  Deletion Policy:        delete
  Last Operation Status:  Success
  Message:                Backend 'fsx-netapp-1-k8s1-san-eco' created
  Phase:                  Bound
Events:
  Type    Reason   Age    From                    Message
  ----    ------   ----   ----                    -------
  Normal  Success  6m42s  trident-crd-controller  Backend 'fsx-netapp-1-k8s1-san-eco' created
```
