### ISSUE TITLE
tridenctl: generate custom yaml - duplicate mapping key "type"

### ISSUE THREAD

**Issue by george-angel** [NetApp/trident#671]
Trident: 21.10.0

Using:

```
tridentctl install --generate-custom-yaml
```

Results in a duplicate declaration of `type: array` in `tridentmirrorrelationships.trident.netapp.io` CRD:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tridentmirrorrelationships.trident.netapp.io
spec:
  group: trident.netapp.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                state:
                  type: string
                  enum:
                  - ""
                  - promoted
                  - established
                  - reestablished
                volumeMappings:
                  type: array
                  items:
                    type: object
                    properties:
                      latestSnapshotHandle:
                        type: string
                      localPVCName:
                        type: string
                      remoteVolumeHandle:
                        type: string
                    required:
                    - localPVCName
                  minItems: 1
                  maxItems: 1
                  type: array
...
```

This is a problem if you use Kustomize (https://kustomize.io/):

```
$ kustomize build cluster/
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 40: mapping key "type" already defined at line 26
```

Apparently duplicate keys aren't valid per yaml 1.2 spec: https://github.com/kubernetes-sigs/kustomize/pull/4096#issuecomment-892929388
