### ISSUE TITLE
Error creating ANF Backend - no virtual networks discovered; volume provisioning may fail until corrected

### ISSUE THREAD

**Issue by lukepearcewp** [NetApp/trident#689]
**Describe the bug**
Unable to create anf backend as it can't find our delegated subnet.  It just gives the error:

    Failed to create backend: problem initializing storage driver 'azure-netapp-files': error initializing azure-netapp-files SDK client. no virtual networks discovered; volume provisioning may fail until corrected

**Environment**
- Trident version: 21.10.1
- Kubernetes version: v1.21.2
- Kubernetes orchestrator: AKS
- NetApp backend types: ANF

**To Reproduce**
Followed the steps here: https://docs.microsoft.com/en-us/azure/aks/azure-netapp-files

Stumped when trying to apply a simple backend e.g.

```
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: trident-backend-anf
  namespace: trident
spec:
  version: 1
  storageDriverName: azure-netapp-files
  subscriptionID: our-subscription-id
  tenantID: out-tenant-id
  location: uksouth
  serviceLevel: Standard
  virtualNetwork: our-vnet
  subnet: our-delegated-subnet
  credentials:
    name: trident-backend-anf-secret
```

**Expected behavior**
To find the delegated subnet and create the backend

**Additional context**

* Our vnet contains two subnets, the 2nd of which is the delegated one.
* The NetApp Files account is in the AKS node resource group (as per setup instructions). However the vnet we use with the delegated subnet is in a different resource group.
* All the resources are in the same location (uksouth).
* I've tried adding `resourceGroups`, using full path versions of `virtualNetwork` and `subnet` (as well as removing them altogether), but nothing seems to work so far.
* Also fyi it looks like the code on master has been refactored a bit; so I looked at the latest version using the Azure Resource Graph and I manually tried the query and it seems to find our delegated subnet correctly.
* EDIT: I also tried adding a volume via the cloud manager using our App Registration - that worked correctly.

The logs seem to show that it ignores the resource group that contains the (vnet with the) delegated subnet.

```
...
time="2022-01-13T10:37:58Z" level=debug msg="Ignoring discovered resource group 'our-resource-group-with-the-delegated-subnet' because it has no ANF accounts or subnets.\n" crdControllerEvent=update requestID=2733dfd3-1966-44c6-9f7f-b9104ad18327 requestSource=CRD
...
time="2022-01-13T10:37:58Z" level=debug msg="Discovery error, not retaining any discovered resources." crdControllerEvent=update error="no virtual networks discovered; volume provisioning may fail until corrected" requestID=2733dfd3-1966-44c6-9f7f-b9104ad18327 requestSource=CRD
time="2022-01-13T10:37:58Z" level=error msg="error discovering resources: no virtual networks discovered; volume provisioning may fail until corrected" crdControllerEvent=update requestID=2733dfd3-1966-44c6-9f7f-b9104ad18327 requestSource=CRD
```
