### ISSUE TITLE
TBC with credential auth failed

### ISSUE THREAD

**Issue by fabian-born** [NetApp/trident#705]
**Describe the bug**
Creation of a TBC with credential authentication failed. 
```
kubectl describe tbc -n trident
. . .
Spec:
. . .
  Deletion Policy:        delete
  Last Operation Status:  Failed
  Message:                Failed to create backend: problem initializing storage driver 'ontap-nas': error initializing ontap-nas driver: could not create Data ONTAP API client: error creating ONTAP API client: error reading SVM details: response code 401 (Unauthorized): incorrect or missing credentials
  Phase:                 
Events:
  Type     Reason  Age                 From                    Message
  ----     ------  ----                ----                    -------
  Warning  Failed  23s (x22 over 10m)  trident-crd-controller  Failed to create backend: problem initializing storage driver 'on tap-nas': error initializing on tap-nas driver: could not create Data ONTAP API client: error creating ONTAP API client: error reading SVM details: response code 401 (Unauthorized): incorrect or missing credentials
```

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 22.01.0
- Trident installation flags used: operator
- Container runtime: 
- Kubernetes version: v1.21.8
- Kubernetes orchestrator: Rancher v2.6.2
- OS: Ubuntu 20.04.
- NetApp backend types: ONTAP 9.10.1 RC1
- Other:

**To Reproduce**
I would like to create a TBC based on Certification auth. I run following steps:
```
openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout k8senv.key -out k8senv.pem -subj "/C=US/ST=NC/L=RTP/O=NetApp/CN=k8sadmin"
security ssl modify -vserver bumblebee -client-enabled true
security cert install -type client-ca -cert-name k8sadmin -vserver bumblebee
security login create -user-or-group-name k8sadmin -application ontapi -authentication-method cert -vserver bumblebee
security login create -user-or-group-name k8sadmin -application http -authentication-method cert -vserver bumblebee
 
```
convert to base64,
create following yaml files
 
```
## secrets_cert.yaml:
apiVersion: v1
kind: Secret
metadata:
  name: ontap-nfs-svm-secret-cert
type: Opaque
stringData:
  clientCertificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tL.....
  clientPrivateKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS .....
```
 
```
## trident-backend-cert.yaml
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-new-cert
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 192.168.69.60
  backendName: tbc-ontap-nas-cert
  svm: bumblebee
  exportPolicy: default
  storagePrefix: cert_
  credentials:
    name: ontap-nfs-svm-secret-cert
```
 
- apply configuration to k8s:
```
kubectl apply -f secrets_cert.yaml -n trident
kubectl apply -f trident-backend-cert.yaml -n trident
```

**Expected behavior**

**Additional context**
I created a backend.json with the cert information and apply it to k8s, tridentctl see the new backend:
```
./tridentctl get backend -n trident  
+------------------------+----------------+--------------------------------------+--------+---------+
|          NAME          | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------------------+----------------+--------------------------------------+--------+---------+
| backend-cert-ontap-nas | ontap-nas      | 330086f3-f3d6-46e8-9055-70d3853fc9de | online |       0 |
+------------------------+----------------+--------------------------------------+--------+---------+
 
```
 
Trident version:
```
./tridentctl version -n trident  
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 22.01.0        | 22.01.0        |
+----------------+----------------+
```

**Comment by disco-stu** [comment]
I'm not sure if its's relevant but you are using `stringData` instead of `data` in your secret definition.

Another problem I ran into the last days was a training newline at the end of the secret (`echo ... | base64` vs `echo -n ... | base64`). However, that was with username and password not cert based authentication.

**Comment by fabian-born** [comment]
Problem was fixed. Thanks to YvosOnTheHub.

Following changes had been made:

secrets_cert.yaml: only the ```clientPrivateKey``` is required.
trident-backend-cert.yaml: adding ```clientCertificate```parameter


my running config now:
```
## trident-backend-cert.yaml
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-new-cert
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 192.168.69.62
  backendName: tbc-ontap-nas-cert
  svm: trident
  exportPolicy: default
  storagePrefix: cert_
  credentials:
    name: ontap-nfs-svm-secret-cert
  clientCertificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS.....
```

```
## secrets_cert.yaml:
apiVersion: v1
kind: Secret
metadata:
  name: ontap-nfs-svm-secret-cert
type: Opaque
stringData:
  clientPrivateKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3F....
```
