### ISSUE TITLE
trident backend config to large to apply with ca signed certificates

### ISSUE THREAD

**Issue by shader1** [NetApp/trident#720]
unable to update/create backend json/yaml file with a ca signed certificate.
it works with shorter shelf signed certificates or user/pw auth combi.

```
root@123 /d/t/trident-installer [1]# kubectl exec trident-csi-xxxx-klb72 -n trident -c trident-main -- tridentctl  version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 22.01.1        | 22.01.1        |
+----------------+----------------+


root@123 /d/t/trident-installer [1]# ./tridentctl create backend -f mu7_cert_backend.json -n trident
error: unable to upgrade connection: <html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>


root@musxl0266 /d/t/trident-installer# ./tridentctl update backend -f mu7_cert_backend.json -n trident
error: unable to upgrade connection: <html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>


root@123 /d/t/trident-installer [1]# kubectl exec trident-csi-84c64f57c5-klb72 -n trident -c trident-main -- tridentctl --debug update backend --base64 ....8804 chars here.. ==
error: unable to upgrade connection: <html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>


root@123 /d/t/trident-installer [1]# cat mu7_cert_backend.yaml
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: nas-backend
spec:
  version: 1
  backendName: nas-backend
  storageDriverName: ontap-nas
  managementLIF: 10.216.96.10
  #dataLIF: 10.0.0.2
  svm: mu7s
  clientCertificate: xxx
  clientPrivateKey: xxx
  trustedCACertificate: xxx
```

**Comment by YvosOnTheHub** [comment]
Hi @shader1 ,

when configuring CERT backends with YAML, as far as I know, the correct process is the following:
- create a Trident SECRET with the clientPrivateKey
- create a Trident TBC with the clientCertificate field & a credentials category referring to the previous object

(I have never tried with the trustedCACertificate, but it should be in either the TBC or the secret...)

example:
```
apiVersion: v1
kind: Secret
metadata:
  name: ontap-nfs-svm-secret-cert
type: Opaque
stringData:
  clientPrivateKey: >-
    copy_and_paste_the_content_of_the_encoded_key_base64_file
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-cert
spec:
  version: 1
  backendName: nas-cert
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.135
  credentials:
    name: ontap-nfs-svm-secret-cert
  clientCertificate: >-
    copy_and_paste_the_content_of_the_encoded_cert_base64_file
```
