### ISSUE TITLE
Certain nodes cannot attach Trident volumes

### ISSUE THREAD

**Issue by tksm** [NetApp/trident#811]
**Describe the bug**

We occasionally have a problem that specific nodes cannot attach Trident volumes. Once it happens, it never recovers until recreating Trident Node pods.

In this situation, pods with Trident volumes get stuck in the ContainerCreating state with the following error.

>  Warning  FailedAttachVolume  14s (x22 over 29m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-310c1228-7477-4fe0-8601-e85365d42d10" : rpc error: code = NotFound desc = node demo-sts-126-w-default-4fc78c0c-hl8kj was not found

After the investigation, we found the following things.

- The issue occurs after performing a rolling update of a Kubernetes cluster.
    - Our cluster update is done by creating and deleting nodes one by one in our environment.
    - [A taint evicts](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions) pods before node deletion.
- Two trident-controller pods could be running simultaneously.
    - A new trident-controller pod is created once the old one gets in the terminating state, so we may have two trident-controller pods for a short time.
    - Though the trident-controller deployment's strategy is [Recreate](https://github.com/NetApp/trident/blob/v23.01.0/cli/k8s_client/yaml_factory.go#L506), it does not prevent having the two pods when eviction.
- The logs [`Added a new node`](https://github.com/NetApp/trident/blob/v23.01.0/frontend/rest/controller_handlers.go#L888) for the affected nodes were found in the old trident-controller pod.

Having two trident-controller pods might be the cause of the problem. Some nodes might [register](https://github.com/NetApp/trident/blob/v23.01.0/frontend/csi/node_server.go#L653) to the old trident-controller, so the new trident-controller does not know those nodes, causing [the not found error](https://github.com/NetApp/trident/blob/v23.01.0/core/orchestrator_core.go#L4754).

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/9250296/223027232-3f4f2dff-0d4e-429f-9a15-a8c33d6c4e98.png">

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 23.01.0
- Trident installation flags used: `silenceAutosupport: true` (Trident Operator)
- Container runtime: containerd://1.6.16
- Kubernetes version: v1.26.1
- Kubernetes orchestrator: Kubernetes
- Kubernetes enabled feature gates:
- OS: Ubuntu 20.04.5 LTS
- NetApp backend types: ONTAP AFF 9.7P13
- Other:

**To Reproduce**

We can confirm that having multiple trident-controller pods causes the issue by the following steps.

1. Setup Trident with trident-operator v23.01.0

2. Remove the trident-operator deployment

```
kubectl delete -n trident deploy/trident-operator
```

3. Set the trident-controller replicas to 5

We manually increase the replicas of the trident-controller deployment since it is difficult to reproduce this issue due to a timing issue.

```
kubectl scale -n trident --replicas 5 deploy/trident-controller
kubectl rollout status -n trident deploy/trident-controller
```

5. Add some new nodes to the cluster

New nodes will register to one of the five trident-controller pods.

```
$ stern -n trident -c trident-main --include "Added a new node" --only-log-lines deployment/trident-controller
trident-controller-5d4f5fcdd7-5s56p trident-main time="2023-03-06T05:20:04Z" level=info msg="Added a new node." handler=AddOrUpdateNode node=demo-tkusumi125-w-default-c1cb56a6-qp6gw requestID=6881b720-403e-4890-95f1-e114a1bdca4b requestSource=REST
trident-controller-5d4f5fcdd7-45s5w trident-main time="2023-03-06T05:20:00Z" level=info msg="Added a new node." handler=AddOrUpdateNode node=demo-tkusumi125-w-default-c1cb56a6-2pmdf requestID=b5dc1928-5c80-4b3a-9671-652ffc43c0b2 requestSource=REST
```

6. Set the trident-controller replicas to 1

```
kubectl scale -n trident --replicas 1 deploy/trident-controller
```

7. Create a StatefulSet with a Trident volume

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: attach-test
spec:
  replicas: 5 # need to adjust
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: attach-test
  serviceName: attach-test
  template:
    metadata:
      labels:
        app: attach-test
    spec:
      containers:
      - command:
        - sh
        - -c
        - trap exit INT TERM; sleep infinity & wait
        image: busybox:latest
        name: container1
        volumeMounts:
        - mountPath: /mnt/pvc
          name: pvc
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: ontap-block
```

Some of the pods will likely get stuck in the ContainerCreating state.

```
$ kubectl get pods -o wide
NAME            READY   STATUS              RESTARTS   AGE     IP            NODE                                       NOMINATED NODE   READINESS GATES
attach-test-0   0/1     ContainerCreating   0          5m48s   <none>        demo-tkusumi125-w-default-c1cb56a6-2pmdf   <none>           <none>
attach-test-1   0/1     ContainerCreating   0          5m48s   <none>        demo-tkusumi125-w-default-c1cb56a6-qp6gw   <none>           <none>
attach-test-2   1/1     Running             0          5m48s   10.26.12.30   demo-tkusumi125-w-default-c1cb56a6-l6d6v   <none>           <none>
attach-test-3   1/1     Running             0          5m48s   10.26.9.27    demo-tkusumi125-w-default-c1cb56a6-sthsp   <none>           <none>
attach-test-4   1/1     Running             0          5m48s   10.26.13.31   demo-tkusumi125-w-default-c1cb56a6-4xnlh   <none>           <none>
```

```
$ kubectl describe pod attach-test-0
...
  Warning  FailedAttachVolume  113s (x10 over 6m8s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-bf76d317-14e3-45cd-864b-35e77c55ebd4" : rpc error: code = NotFound desc = node demo-tkusumi125-w-default-c1cb56a6-2pmdf was not found
```

**Expected behavior**

All nodes can attach Trident volumes.

**Additional context**
