### ISSUE TITLE
tridentControllerPluginNodeSelector/tridentNodePluginNodeSelector  won't work with "true" value

### ISSUE THREAD

**Issue by kmizumar** [NetApp/trident#899]
**Describe the bug**

Trying to use `tridentControllerPluginNodeSelector` and `tridentNodePluginNodeSelector` with helm chart setup providing the following values per yaml file would fail:

```
tridentControllerPluginNodeSelector:
  node-role.kubernetes.io/worker: "true"

tridentNodePluginNodeSelector:
  node-role.kubernetes.io/worker: "true"
```

This bug is exactly the same one which is reported in [new nodeSelectors are not working when label value contains "true"]( https://github.com/NetApp/trident/issues/700).

According to this update https://github.com/NetApp/trident/issues/700#issuecomment-1195891827, it's fixed in Trident 22.07 release, but some users reported it still exists in 23.04.0, 23.07.0, 23.10, and I hit this bug with 24.02 release.

I confirmed that Parajwal V brought in this problem again on 03/06/23 98c0d9ae, which Arnav Srivastava had solved on 06/01/22 a53cf69e.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 24.02
- Trident installation flags used: helm setup with above custom yaml
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: 1.28.3
- Kubernetes enabled feature gates: -
- OS: Ubuntu 24.04LTS
- NetApp backend types: ONTAP NAS
- Other:
  - Kustomize version: 5.3.0

**To Reproduce**
see above.

**Expected behavior**
node selector handles the value `"true"` correctly.
