### ISSUE TITLE
Trident-Protect AppVault to pull S3 endpoint from ConfigMap

### ISSUE THREAD

**Issue by lunderhage** [NetApp/trident#988]
**Describe the solution you'd like**
We are testing out trident-protect as a backup solution along with Trident. We are using an operator to manage S3 buckets and we do not know the exact name and endpoint address to an ObjectBucketClaim before it has been created. However, the ObjectBucketClaim being bound leads to having a Secret with credentials (that we already use) and a ConfigMap with endpoint information. I would like to be able to pull endpoint configuration from a ConfigMap rather than entering it directly in the AppVault like this:

```yaml
spec:
  providerConfig:
    s3:
      bucketName: ...
      endpoint: ...
```

How about something like this?
```yaml
spec:
  providerConfig:
    s3:
      bucketName:
        valuesFromConfigMap:
          name: <cm_name>
          key: <cm_key>
      endpoint:
        valuesFromConfigMap:
          name: <cm_name>
          key: <cm_key>
```

**Describe alternatives you've considered**
We are looking into other backup solutions that might be more flexible for us.
