### ISSUE TITLE
Help needed in understanding "nameTemplate" - volumes always get created with UUID

### ISSUE THREAD

**Issue by b2cc** [NetApp/trident#995]
**Describe the solution you'd like**
I have configured a `nameTemplate` in the `trident BackendConfiguration` and would like volumes to be named in the same way as the `PVC`s are named on kubernetes.

However trident seems to ignore the configuration and always creates volumes in the format `pvc_76cded10_75ef...`.

The documentation is very sparse about this feature, and, in places, also feels wrong to me. E.g.:
* https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html#minimal-configuration-examples , in `Backend configuration example with nameTemplate` seems to mix up YAML and JSON. If this is actually meant like this, please explain how because I wasn't able to derive valid YAML from this example
* https://docs.netapp.com/us-en/trident/trident-use/vol-custom-name.html : Again, this is in JSON format, and the documentation is not clear if this is a `tridentBackend` or `tridentBackendConfiguration`. 

There is no complete working example including a PVC declaration that would make use of this, nor any examples and their expected outcome. It is really hard to understand how this is supposed to work.

**Describe alternatives you've considered**
n/a

**Additional context**
My configuration: Ontap on-prem FAS storage system with `ontap-nas` driver. I created the `tridentBackendConfiguration`, which creates the `tridentBackend` as expected and gets registered with the storage. It works to the point where I can create and manage volumes, however the templating feature doesn't work and I always end up with just the UUID volume name.

`tridentBackendConfiguration`
```
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: fas-tbc
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 10.1.100.26
  dataLIF: 10.1.100.29
  backendName: fas
  svm: svm_nas
  credentials:
    name: fas-backend-secret
  defaults:
    spaceReserve: volume
    encryption: 'true'
    unixPermissions: "0777"
    securityStyle: unix
    nameTemplate: "{{.volume.Name}}_{{.labels.cluster}}_{{.volume.Namespace}}_{{.volume.RequestName}}"
  labels:
    cluster: k8s-example-com
    PVC: "{{.volume.Namespace}}_{{.volume.RequestName}}"
  autoExportPolicy: true
  autoExportCIDRs:
    - 10.1.100.0/24`
```

PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trident-test-volume
  namespace: trident
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ontap-nfs
```

trident logs during volume creation:
```
trident-controller-64965d9479-nmwrr csi-provisioner I0330 12:57:44.215888       1 event.go:389] "Event occurred" object="trident/trident-test-volume" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"trident/trident-test-volume\""
trident-controller-64965d9479-nmwrr csi-provisioner I0330 12:57:48.848153       1 controller.go:958] successfully created PV pvc-76cded10-75ef-422e-93ca-98ef25621dc4 for PVC trident-test-volume and csi volume name pvc-76cded10-75ef-422e-93ca-98ef25621dc4
trident-controller-64965d9479-nmwrr csi-provisioner I0330 12:57:48.862370       1 event.go:389] "Event occurred" object="trident/trident-test-volume" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ProvisioningSucceeded" message="Successfully provisioned volume pvc-76cded10-75ef-422e-93ca-98ef25621dc4"
```

And the PV/PVC look like this:
```
oc get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS
trident-test-volume   Bound    pvc-76cded10-75ef-422e-93ca-98ef25621dc4   10Gi       RWX            ontap-nfs
```

Could you please help me understand how this needs to be configured to get meaningful volume names on the storage side? Any help is very much appreciated.

Thanks in advance and all the best!
